kind: Service 
apiVersion: v1 
metadata:
  name: nginx-blue-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginxblue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    