apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxblue

  template: 
    metadata:
      labels: 
        app: nginxblue   
    spec:
      containers:
      - name: nginxblue
        image: nginx:1.14.2
        ports:
        - containerPort: 80    