apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxgreen

  template: 
    metadata:
      labels: 
        app: nginxgreen   
    spec:
      containers:
      - name: nginxgreen
        image: nginx:1.14.2
        ports:
        - containerPort: 80    