kind: Service 
apiVersion: v1 
metadata:
  name: nginx-green-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginxgreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    