apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity5

  template: 
    metadata:
      name: udacitypod
      labels: 
        app: udacity5       
    spec:
      containers:
      - name: udactycontainer
        image: 478288121115.dkr.ecr.us-east-1.amazonaws.com/microservice-udacity-5:latest
        ports:
        - containerPort: 80    