apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template: 
    metadata:
      labels: 
        app: nginx      
    spec:
      containers:
      - name: nginx
        image: 478288121115.dkr.ecr.us-east-1.amazonaws.com/microservice-udacity-5:latest
        ports:
        - containerPort: 80    