kind: Service 
apiVersion: v1 
metadata:
  name: flask-green-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: flaskgreen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    