apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskgreen

  template: 
    metadata:
      labels: 
        app: flaskgreen   
    spec:
      containers:
      - name: flaskgreen
        image: 478288121115.dkr.ecr.us-east-1.amazonaws.com/microservice-udacity-5
        ports:
        - containerPort: 80    